config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :blogs, only:[:index, :new , :create, :edit, :update, :destroy, :show] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only:[:new, :create] do
  collection do
      post :confirm
    end
  end

  resources :blogs do
    resources :comments #ネスト(入れこ)している(/blogs/:blog_id/commentsとなる)

    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index, :show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'top#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title,presence: true #titleにバリデーションを設定・空入力を禁止

    belongs_to :user #Blogモデルのレコードがユーザーモデルのレコードに属する設定

    # Commentモデルのアソシエーションを設定
    has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  #ログインしていなければblogを使用できないようにする(Deviseのauthenticate_user!メソッドを使用)
  before_action :authenticate_user!
  before_action :set_blog, only:[:show, :edit, :update, :destroy] #共通のメソッドを事前呼び出し

  #すべてのブログを取得
  def index
    @blogs = Blog.all
    # binding.pry #ブレークポイントを仕込む
  end

  #showアクションの定義：コメントの入力フォームと一覧を表示するためインスタンスを2つ生成
  def show
    @comment = @blog.comments.build
    @comments = @blog.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  #新規作成
  def new

    if params[:back] #戻るボタンが押された場合
      @blog = Blog.new(blogs_params)
    else
      #インスタンス変数(viewファイルに渡す変数)の宣言
      @blog = Blog.new
    end

  end

  def create
    @blog = Blog.new(blogs_params)
    #Blog.create(blogs_params) #ストロングパラメータを引数に渡す

    #user_idをカラムに代入する(current_userメソッドを使用する)
    @blog.user_id = current_user.id
    #@name. = Blog.find(current_user.id)

    #バリデーション成否の確認
    if @blog.save  #成功時
      redirect_to blogs_path,notice:"ブログを作成しました！"
      #作成と同時にメールを送信(使用するメソッドはdeliverメソッド)
      NoticeMailer.sendmail_blog(@blog).deliver
      #blogコントローラのindexアクションにリダイレクトする　noticeオプションでフィードバックメッセージを表示
    else#失敗時
      render 'new' #同じ画面の再描画
    end

  end
  #ここまで

  #既存ブログを編集
  #編集する内容の入力
  def edit
  end

  #編集した内容で更新する
  def update
    if @blog.update(blogs_params) #値を更新するためにupdateメソッドを使用(引数はblogの内容)
      redirect_to blogs_path,notice:"ブログを更新しました！"#indexアクションにリダイレクト
    else
      render 'new' #再描画
    end
  end
  #ここまで

  #既存ブログの消去
  def destroy
    @blog.destroy #値を削除するためにdestroyメソッドを使用(引数は不要)
    redirect_to blogs_path,notice:"ブログを削除しました！" #indexアクションにリダイレクト
  end
  #ここまで

  #入力内容確認用
  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid? #確認時のバリデーション
  end
  #ここまで

  private
  #ストロングパラメータの設定
  def blogs_params
    params.require(:blog).permit(:title, :content) #paraｍsメソッドで取得した中でblogに関してtitleとcontentだけを許可する
  end

  def set_blog
      # edit, update, destroyで共通コード
      #引数が一つの場合はストロングパラメータを使用する必要はない
     @blog = Blog.find(params[:id]) #選択された該当のidの内容取得
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
    
    #newアクションとeditアクション時の表示ビューの分岐
    def choose_new_or_edit 
        if action_name == "new" || action_name == "confirm"
            confirm_blogs_path
        elsif action_name =="edit"
            blog_path
        end
    end
end

app/views/blogs/_form.html.erb
<!--フォームの宣言-->
<%=form_for(@blog,url:choose_new_or_edit ) do |f| %>　<!--分岐時にヘルパーメソッドの利用-->

  <%= f.error_messages! %>

  <%= f.label :タイトル %> <!--指定したモデルカラムへのラベルを作成-->
  <%= f.text_field :title,class: 'form-control' %> <!--指定したモデルカラムへのテキスト欄（フォーム）を作成-->
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content,class: 'form-control' %>
  <br>
  <%= f.submit '投稿',class: 'btn btn-primary btn-block' %>
<% end %>
<!--formの終わりを宣言-->

<%=link_to "ブログ一覧画面に戻る",blogs_path %>

app/views/blogs/confirm.html.erb
<!--入力確認用フォームの宣言-->
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    
    <h3>以下の内容で送信する</h3>
    
    <%=form_for(@blog) do |f| %> 
      <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定。 -->
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
    
      <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力 -->
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "登録する",class: 'btn btn-primary btn-block' %>
    <% end %>
    
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name:'back',class: 'btn btn-default btn-block'  %>
    <% end %>
    
    <!--前のページへ戻る-->
    <!--<%= link_to '戻る', :back %>-->
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<!--以下はbootstrapなしの標準の書き方-->
<!--<p><%= notice %></p> <!--フィードバックメッセージの表示-->

<!--<h1>ブログ一覧</h1>-->

<!--<% @blogs.each do |blog| %>-->
<!--  <p>タイトル:<%= blog.title %></p>-->
<!--  <p>本文:<%= blog.content %></p>-->
<!--  <%= link_to "ブログを編集する", edit_blog_path(blog.id) %> <br><!--ブログのidを取得して表示する-->
<!--  <%= link_to "ブログを削除する", blog_path(blog.id), method: :delete, data: {confirm: '本当に削除していいですか？'} %> -->
  <!--link_toメソッドはデフォルトでHTTPメソッドをgetで送信するのでdestroyアクションへのリクエストはdeleteメソッドを指定-->
<!--<% end %>-->

<!--<br>-->
<!--<%= link_to "ブログを作成する",new_blog_path %>-->
<!--<br>-->
<!--<%= link_to "お問い合わせ",new_contact_path %>-->

<!--以下はbootstrap使用時の書き方-->
<div class= "container">
  <div class= "wrapper col-md-8 col-md-offset-2 col-sm-10">

  <p><%=notice%></p> <!--フィードバックメッセージの表示-->
  <h1>ブログ一覧</h1>
  <%= link_to "ブログを作成する",new_blog_path,class:'btn btn-default' %>
  <!--<%= link_to "お問い合わせ",new_contact_path, class:'btn btn-default' %>-->
  <% @blogs.each do |blog| %>
  <div class="row">
    <!-- ブログのタイトルにlink_toでリンクを設定 -->
    <%= link_to blog_path(blog) do %>
      <h4><strong><%= blog.title %></strong></h4>
    <% end %>
      <p><%= blog.content %></p>
      <!--  プロフィール画像と投稿者の表示 -->
      <%# binding.pry %>
      <p><%= profile_img(Blog.find(blog.id).user)%>
        <%= Blog.find(blog.id).user.name %>さんが投稿しました </p><!--作成したユーザー名の表示-->
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
  <% end %>
  </div>
</div>

<!--トップに戻るボタンの表示-->
<div id="blog-page-top-btn" class="page-top-btn">
  <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/blogs/new.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2> 
    <p id="notice"><%=notice %></p>
    <%= render 'form' %>
 </div>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @blog.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @blog.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @blog.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <!-- id=commnets_areaにてJSでHTMLを書き換え実施 -->
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
    </div>
    <br/>
    <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>

    <% if current_user.id == @blog.user_id %>
      <%= link_to '編集', edit_blog_path(@blog), class:"btn btn-block btn-primary" %>
    <% end %>
      <%= link_to '戻る', blogs_path, class:"btn btn-block btn-default" %>
  </div>
</div>