config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :blogs, only:[:index, :new , :create, :edit, :update, :destroy, :show] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only:[:new, :create] do
  collection do
      post :confirm
    end
  end

  resources :blogs do
    resources :comments #ネスト(入れこ)している(/blogs/:blog_id/commentsとなる)

    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index, :show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'top#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  #以下のメソッドhas_many :blogs により子モデル（blog）が複数紐づくアソシエーションを定義
  has_many :blogs,dependent: :destroy

  # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy

  # 相互フォローの設定
  # usersテーブルのidカラムと参照関係を持つカラムを「follower_id」カラムであると定義
  has_many :relationships,foreign_key: "follower_id", dependent: :destroy
  #reverse_relationshipsというアソシエーションを定義します。
  has_many :reverse_relationships,foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable

  mount_uploader :avatar,AvatarUploader

  #指定のユーザをフォローする
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  #フォローしているかどうかを確認する
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  #指定のユーザのフォローを解除する
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  #facebook用
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
      user = User.find_by(email: auth.info.email)

       unless user
        user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.save(validate: false)
      end
      user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

# update_with_passwordのオーバーライド
#　providerが空:superでupdate_with_passwordに記述されている内容を上書き
#  providerが存在:current_passwordを削除してパスワードなしでも更新
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def self.create_unique_string
    SecureRandom.uuid #uidメソッドでランダムな文字列を作成
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  #Facebookサインインボタンが押された時のメソッド
  def facebook
  @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
    #binding.pry

  end

  #twitterサインインボタンが押された時のメソッド
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
#Devise::RegistrationsControllerを継承
class Users::RegistrationsController < Devise::RegistrationsController

#devise/registrations_controllerのbuild_resource(hash=nil)を上書き
  def build_resource(hash=nil)

    # uidカラムにランダムなuidを代入
    hash[:uid] = User.create_unique_string
    super #元のメソッドに記述されたものを代入
    # binding.pry
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

  end

  def show
    # 特定のユーザーidのユーザーを取得
    @user = User.find(params[:id])
    # binding.pry
    #フォローしたユーザーの値を取得
    @followers = @user.followed_users
    #フォローされたユーザーの値を取得
    @followed_users = @user.followers
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>" ,class="container-child col-md-2 col-sm-4 col-xs-6">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/_followfollower.html.erb
<div class="container-child col-md-2 col-sm-4 col-xs-6 ">
  <p>フォローされているユーザー</p>
  <% @followers.each do |follower| %>
  <%= profile_img(follower) %>
  <!-- フォロワーの表示　-->
  <%= follower.name %>
  <!-- フォローしたユーザーの表示 -->
  <%#= user.followers.find(3).name %>
  <br/>
  <% end %>
</div>

<div class="container-child col-md-2 col-sm-4 col-xs-6 ">
  <p>フォローしているユーザー</p>
  <% @followed_users.each do |followed_user| %>
  <%= profile_img(followed_user) %>
  <!-- フォロワーの表示　-->
  <%= followed_user.name %>
  <!-- フォローしたユーザーの表示 -->
  <%#= user.followers.find(3).name %>
  <br/>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー</h2>
  <% @users.each do |user| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <%= profile_img(user) %>
        <%= link_to user_path(user) do %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
          <h4>ユーザー名：<strong><%= user.name%></strong></h4>
        <% end %>
        <p>email:<%= user.email %></p>
        <%= render 'follow_form', user: user %>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>つながり一覧</h2>
  <!-- <p><%= current_user.name %>でログイン中！</p> -->
  <%=render partial:'followfollower' %>
</div>